###
GET http://localhost:9090/books

###
POST http://localhost:9090/books
Content-Type: application/json

{
    "Id": "3", "Title": "Two", "Author": "A2"
}

###
POST http://localhost:9090/login
Content-Type: application/json

{
    "username": "ebarstock0",
    "password": "rW1,(}Qi4f"
}
